### PR TITLE
Fixed #30 : StartNVMM exits without any error message

### LINKED ISSUE #30: StartNVMM exits without any error message
When the NVMM directory is already available and there is no permission for the directories, NVMM exits without throwing any error. Improve the error handling in NVMM in throw the error to user rather than failing silently.

### PR DESCRIPTION
**Pull request by cynara-justine**
Fixed #30 : NVMM code changes for StartNVMM exits without any error message.  Changes are being made to OpenFAM code also for fixing this issue.  Added a return value for StartNVMM() and added conditions to handle exceptions and error scenarios.

### CODE REVIEW

File: src/memory_manager.cc [hunk 1]
```diff
@@ -102,8 +154,9 @@ void StartNVMM(std::string base, std::string user) {
         ErrorCode ret = root_shelf.Create();
         if (ret!=NO_ERROR && ret != SHELF_FILE_FOUND)
         {
-            LOG(fatal) << "NVMM: Failed to create the root shelf file " << config.RootShelfPath;
-            exit(1);
+            LOG(fatal) << "NVMM: Failed to create the root shelf file: error code "<<ret << config.RootShelfPath;
```
Comment (mashoodk) [inline src/memory_manager.cc:157]: clang-format

Comment (mashoodk) [inline src/memory_manager.cc:157]: clang-format

File: src/memory_manager.cc [hunk 2]
```diff
@@ -76,23 +77,74 @@ namespace nvmm {
...
+    	if (boost::filesystem::exists(shelf_base_path) == false)
+	{
+        	LOG(fatal) << "NVMM: LFS/tmpfs does not exist?" << config.ShelfBase;
+	        std::cout << "NVMM: LFS/tmpfs does not exist?" << std::endl;
+        	return SHELF_BASE_PATH_DOES_NOT_EXIST;
+    	}
+    }
+    catch (boost::filesystem::filesystem_error const &err)
+    {
+        if(err.code().value() == 2)
```
Comment (mashoodk) [inline src/memory_manager.cc:137]: Why is there a seperate check for value equals 2

Comment (mashoodk) [inline src/memory_manager.cc:137]: Why is there a seperate check for value equals 2

**Review by mashoodk — CHANGES_REQUESTED** [review]

**Review by mashoodk — APPROVED** [review]
